In [14]:
import numpy as np
test = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
                [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
                [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
                [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
                [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
                [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
                [7, 7, 7, 7, 7, 7, 7, 7, 7, 7], 
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
print(test)
# dWf[:-1, :].reshape(nc-1, 2, N2).sum(axis=1) # sum of 2 fine adjacent increments, ignore final point
test[:-1, :].reshape(4, 2, 10).sum(axis=1)

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [0 0 0 0 0 0 0 0 0 0]]


array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
       [13, 13, 13, 13, 13, 13, 13, 13, 13, 13]])

In [ ]:
import sys, os
import numpy as np
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
from utils.mg_example_parabolic import parabolic_example_scheme
T = 0.25; nx = 20; lam = 0.25; n_samples = 5
u_samples = parabolic_example_scheme(T, nx, lam, n_samples)
h = 1 / nx
QoIs = h * np.sum(u_samples**2, axis=0)
expected = QoIs.mean()
print(expected)

Number of time steps: 399, dt: 0.0006250000000000001, dx: 0.05
Time step 0/399


10.949694074390107
