In [1]:
import numpy as np

In [29]:
N = 4
A = np.arange(N**2).reshape((N,N))
B = A.copy()
print(A)
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [30]:
C = np.dot(A, B)
print(C)

[[ 56  62  68  74]
 [152 174 196 218]
 [248 286 324 362]
 [344 398 452 506]]


In [31]:
C_prime = np.zeros((N,N))
for i in range(len(A)):
    for j in range(len(B)):
        for k in range(len(A)):
            C_prime[i, j] += A[i, k] * B[k, j] 
# This one makes sense. For each row, for each column (these could be the other way around) I have to move along the rows of A and the columns of B and 
# add their contributions.
print(C_prime)

[[ 56.  62.  68.  74.]
 [152. 174. 196. 218.]
 [248. 286. 324. 362.]
 [344. 398. 452. 506.]]


In [34]:
C_pprime = np.zeros((N,N))
tile_size = 2
for ii in range(0, N, tile_size):
    for jj in range(0, N, tile_size):
        for kk in range(0, N, tile_size):
            print(ii, jj, kk, )
            print(C_pprime)
            for i in range(ii, ii + tile_size):
                for j in range(jj, jj + tile_size):
                    for k in range(kk, kk + tile_size):
                        C_pprime[i,j] += A[i,k] * B[k,j]

print(C_pprime)
                    

0 0 0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
0 0 2
[[ 4.  5.  0.  0.]
 [20. 29.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
0 2 0
[[ 56.  62.   0.   0.]
 [152. 174.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
0 2 2
[[ 56.  62.   6.   7.]
 [152. 174.  38.  47.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
2 0 0
[[ 56.  62.  68.  74.]
 [152. 174. 196. 218.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
2 0 2
[[ 56.  62.  68.  74.]
 [152. 174. 196. 218.]
 [ 36.  53.   0.   0.]
 [ 52.  77.   0.   0.]]
2 2 0
[[ 56.  62.  68.  74.]
 [152. 174. 196. 218.]
 [248. 286.   0.   0.]
 [344. 398.   0.   0.]]
2 2 2
[[ 56.  62.  68.  74.]
 [152. 174. 196. 218.]
 [248. 286.  70.  87.]
 [344. 398. 102. 127.]]
[[ 56.  62.  68.  74.]
 [152. 174. 196. 218.]
 [248. 286. 324. 362.]
 [344. 398. 452. 506.]]


In [ ]:
A[i,k]